spring:
  application:
    name: API-REG
server:
  port: 8761
endpoints:
  shutdown:
    enabled: true
    sensitive: false
eureka:
  instance:
    hostname: localhost
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 3
    preferIpAddress: false
  client:
    registerWithEureka: true
    fetchRegistry: true