spring:
  application:
    name: OAUTH
  zipkin:
    baseUrl: http://ip-172-31-12-174.ap-northeast-2.compute.internal:9411
  sleuth:
    sampler:
      percentage: 0.2
  http:
    encoding:
      force: true
      charset: UTF-8
server:
  port: 8080
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
logging:
  config: classpath:logback-dev.xml